platforms:
  esp32:
    board: esp32:esp32:esp32
  esp8266:
    board: esp8266:esp8266:generic
    
compile:
  libraries:
    - mqtt
    - RadioLib
    - ArduinoJson
  platforms:
    - esp32
    - esp8266

unittest:
  libraries:
    - mqtt
    - RadioLib
    - ArduinoJson
  platforms:
    - esp32
    - esp8266
