mqtt:
  sensor:
    - name: "Temperatuur"
      unique_id: "Bresstat_temp"
      state_topic: "ESPWeather/961c/data"
      value_template: "{{ value_json.temp_c }}"
      device_class: "temperature"
      unit_of_measurement: "°C"
      device:
        name: "Weerstation"
        identifiers: "Bresser"
        manufacturer: "Chris"
        model: "Bresser MQTT"
    - name: "Dauwpunt"
      unique_id: "Bresstat_dew"
      state_topic: "ESPWeather/extra"
      value_template: "{{ value_json.dewpoint_c }}"
      device_class: "Temperature"
      unit_of_measurement: "°C"
      device:
        name: "Weerstation"
        identifiers: "Bresser"
        manufacturer: "Chris"
        model: "Bresser MQTT"
    - name: "Gevoelstemperatuur"
      unique_id: "Bresstat_feel"
      state_topic: "ESPWeather/extra"
      value_template: "{{ value_json.perceived_temp_c }}"
      device_class: "Temperature"
      unit_of_measurement: "°C"
      device:
        name: "Weerstation"
        identifiers: "Bresser"
        manufacturer: "Chris"
        model: "Bresser MQTT"
    - name: "Luchtvochtigheid"
      unique_id: "Bresstat_humi"
      state_topic: "ESPWeather/961c/data"
      value_template: "{{ value_json.humidity }}"
      device_class: "humidity"
      unit_of_measurement: "%"
      device:
        name: "Weerstation"
        identifiers: "Bresser"
        manufacturer: "Chris"
        model: "Bresser MQTT"
    - name: "ID"
      unique_id: "Bresstat_id"
      state_topic: "ESPWeather/961c/data"
      value_template: "{{ value_json.id }}"
      device:
        name: "Weerstation"
        identifiers: "Bresser"
        manufacturer: "Chris"
        model: "Bresser MQTT"
    - name: "Kanaal"
      unique_id: "Bresstat_ch"
      state_topic: "ESPWeather/961c/data"
      value_template: "{{ value_json.ch }}"
      device:
        name: "Weerstation"
        identifiers: "Bresser"
        manufacturer: "Chris"
        model: "Bresser MQTT"
    - name: "Batterij"
      unique_id: "Bresstat_batt"
      state_topic: "ESPWeather/961c/data"
      value_template: "{{ value_json.battery_ok }}"
      device:
        name: "Weerstation"
        identifiers: "Bresser"
        manufacturer: "Chris"
        model: "Bresser MQTT"
    - name: "Windvlaag"
      unique_id: "Bresstat_gust"
      state_topic: "ESPWeather/961c/data"
      value_template: "{{ value_json.wind_gust }}"
      device_class: "wind_speed"
      unit_of_measurement: "km/h"
      device:
        name: "Weerstation"
        identifiers: "Bresser"
        manufacturer: "Chris"
        model: "Bresser MQTT"
    - name: "Windsnelheid"
      unique_id: "Bresstat_wind"
      state_topic: "ESPWeather/961c/data"
      value_template: "{{ value_json.wind_avg }}"
      device_class: "wind_speed"
      unit_of_measurement: "km/h"
      device:
        name: "Weerstation"
        identifiers: "Bresser"
        manufacturer: "Chris"
        model: "Bresser MQTT"
    - name: "Windhoek"
      unique_id: "Bresstat_dirdeg"
      state_topic: "ESPWeather/961c/data"
      value_template: "{{ value_json.wind_dir }}"
      unit_of_measurement: "Graden"
      device:
        name: "Weerstation"
        identifiers: "Bresser"
        manufacturer: "Chris"
        model: "Bresser MQTT"
    - name: "Windrichting"
      unique_id: "Bresstat_dircar"
      state_topic: "ESPWeather/extra"
      value_template: "{{ value_json.wind_dir_txt }}"
      device:
        name: "Weerstation"
        identifiers: "Bresser"
        manufacturer: "Chris"
        model: "Bresser MQTT"
    - name: "Windvlaag bft"
      unique_id: "Bresstat_gust_bft"
      state_topic: "ESPWeather/extra"
      value_template: "{{ value_json.wind_gust_bft }}"
      device_class: "wind_speed"
      unit_of_measurement: "Beaufort"
      device:
        name: "Weerstation"
        identifiers: "Bresser"
        manufacturer: "Chris"
        model: "Bresser MQTT"
    - name: "Windsnelheid bft"
      unique_id: "Bresstat_avg_bft"
      state_topic: "ESPWeather/extra"
      value_template: "{{ value_json.wind_avg_bft }}"
      device_class: "wind_speed"
      unit_of_measurement: "Beaufort"
      device:
        name: "Weerstation"
        identifiers: "Bresser"
        manufacturer: "Chris"
        model: "Bresser MQTT"
    - name: "UV-index"
      unique_id: "Bresstat_UV"
      state_topic: "ESPWeather/961c/data"
      value_template: "{{ value_json.uv }}"
      device:
        name: "Weerstation"
        identifiers: "Bresser"
        manufacturer: "Chris"
        model: "Bresser MQTT"
    - name: "Lichtintensiteit"
      unique_id: "Bresstat_light"
      state_topic: "ESPWeather/961c/data"
      value_template: "{{ value_json.wind_gust }}"
      unit_of_measurement: "kLux"
      device:
        name: "Weerstation"
        identifiers: "Bresser"
        manufacturer: "Chris"
        model: "Bresser MQTT"
    - name: "Neerslag totaal"
      unique_id: "Bresstat_rain"
      state_topic: "ESPWeather/961c/data"
      value_template: "{{ value_json.rain }}"
      device_class: "precipitation"
      unit_of_measurement: "mm"
      device:
        name: "Weerstation"
        identifiers: "Bresser"
        manufacturer: "Chris"
        model: "Bresser MQTT"
    - name: "Neerslag vandaag"
      unique_id: "Bresstat_rain_d"
      state_topic: "ESPWeather/961c/data"
      value_template: "{{ value_json.rain_d }}"
      device_class: "precipitation"
      unit_of_measurement: "mm"
      device:
        name: "Weerstation"
        identifiers: "Bresser"
        manufacturer: "Chris"
        model: "Bresser MQTT"
    - name: "Neerslag laatste uur"
      unique_id: "Bresstat_rain_h"
      state_topic: "ESPWeather/961c/data"
      value_template: "{{ value_json.rain_h }}"
      device_class: "precipitation"
      unit_of_measurement: "mm"
      device:
        name: "Weerstation"
        identifiers: "Bresser"
        manufacturer: "Chris"
        model: "Bresser MQTT"
    - name: "Neerslag deze week"
      unique_id: "Bresstat_rain_w"
      state_topic: "ESPWeather/961c/data"
      value_template: "{{ value_json.rain_w }}"
      device_class: "precipitation"
      unit_of_measurement: "mm"
      device:
        name: "Weerstation"
        identifiers: "Bresser"
        manufacturer: "Chris"
        model: "Bresser MQTT"
    - name: "Neerslag deze maand"
      unique_id: "Bresstat_rain_m"
      state_topic: "ESPWeather/961c/data"
      value_template: "{{ value_json.rain_m }}"
      device_class: "precipitation"
      unit_of_measurement: "mm"
      device:
        name: "Weerstation"
        identifiers: "Bresser"
        manufacturer: "Chris"
        model: "Bresser MQTT"
    - name: "Signaal"
      unique_id: "Bresstat_signal"
      state_topic: "ESPWeather/961c/rssi"
      device_class: "signal_strength"
      unit_of_measurement: "dB"
      device:
        name: "Weerstation"
        identifiers: "Bresser"
        manufacturer: "Chris"
        model: "Bresser MQTT"
    - name: "Status"
      unique_id: "Bresstat_stat"
      state_topic: "ESPWeather/status"
      device:
        name: "Weerstation"
        identifiers: "Bresser"
        manufacturer: "Chris"
        model: "Bresser MQTT"